Feat/cache in useGasEstimation
BuidlGuidl/hacked-wallet-recovery pull request #67
Opened 2024-12-26 19:58 UTC by portdeveloper

### This PR 
-> Implements a caching mechanism that i got from ~~cursor~~ 
-> Removes the default bg api key for alchemy
-> Increases the interval for getting the estimate gas to 15 secs

2025-01-01 15:40 UTC, escottalexander commented on packages/nextjs/hooks/flashbotRecoveryBundle/useGasEstimation.ts
> +    if (now - lastBaseFeeTimestamp.current < 12000 && !lastBaseFee.current.isZero()) {
Nice. This is a bit of a tradeoff because potentially we will trail the current block by 11.99 seconds but I don't think it matters that much. Worth the call savings.

2025-01-01 15:57 UTC, escottalexander requested changes
Great improvements all around but I want to get your opinion on one possible improvement. Nice work!

2025-01-01 15:57 UTC, escottalexander commented on packages/nextjs/hooks/flashbotRecoveryBundle/useGasEstimation.ts
> +    const block = await publicClient.getBlock({ blockNumber: blockNumberNow });
What if we remove the call on 42 and just get the latest block by passing "latest"? `publicClient.getBlock({ blockNumber: "latest" })`. One call saved.

2025-01-01 15:57 UTC, escottalexander commented on packages/nextjs/hooks/flashbotRecoveryBundle/useGasEstimation.ts
> +        estimates = lastEstimates.current;
This does seem to work, which is great! The simulateExecutionBundle call costs more than normal calls so a huge win.

2025-01-02 00:51 UTC, portdeveloper commented on packages/nextjs/hooks/flashbotRecoveryBundle/useGasEstimation.ts
> +    const block = await publicClient.getBlock({ blockNumber: blockNumberNow });
It doesn't explicitly say this here but I believe a call to getBlock without any parameters will get us the latest block as blockTag is "latest" by default.

source: https://viem.sh/docs/actions/public/getBlock.html

modified the example from viem docs to check 
![image](https://github.com/user-attachments/assets/9be51acb-13f4-4776-82fc-6db410073ee6)

2025-01-02 01:06 UTC, escottalexander approved these changes
Perfect! Nice work on this one!

2025-01-02 01:06 UTC, merged